/**:
  ros__parameters:
    wheel_radius: 0.132 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.08 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 0.501 # between front wheel center and rear wheel center
    wheel_tread: 0.462 # between left wheel center and right wheel center
    front_overhang: 0.196 # between front wheel center and vehicle front
    rear_overhang: 0.196 # between rear wheel center and vehicle rear
    left_overhang: 0.04 # between left wheel center and vehicle left
    right_overhang: 0.04 # between right wheel center and vehicle right
    vehicle_height: 1.2
    max_steer_angle: 3.14 # [rad]





