/**:
  ros__parameters:
    map_frame: map
    arrival_check_angle_deg: 45.0 #到达目标点时的角度检查阈值，单位为度
    arrival_check_distance: 1.0 #到达目标点的距离检查阈值，单位为米
    arrival_check_duration: 1.0 #到达目标点后需要停留的时间，单位为秒
    goal_angle_threshold_deg: 45.0 #目标点方向的角度阈值，单位为度
    enable_correct_goal_pose: false #是否启用目标点姿态校正功能(在中间 正方向)
    reroute_time_threshold: 10.0 # 重新规划路径的时间阈值
    minimum_reroute_length: 30.0 # 触发重新规划的最小路径长度
    consider_no_drivable_lanes: true # 是否考虑不可驾驶车道 This flag is for considering no_drivable_lanes in planning or not.
    check_footprint_inside_lanes: true
    allow_reroute_in_autonomous_mode: true #是否允许在自动驾驶模式下进行路径重新规划


# mission_planning 任务规划配置: 负责全局路径规划，从起点到终点的整体路线规划
#  - 在lanelet地图上规划从起点到终点的路线
#  - 判断是否到达目标点
#  - 决定何时需要重新规划路径
#  - 检查车辆是否在可行驶车道内
